import "./globals.css";
import { Footer } from "./componets/Footer/Footer";
import Navbar from "./componets/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" antialiased overflow-x-hidden w-screen">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
